import { Meteor } from 'meteor/meteor';
import { keys } from 'lodash';
import { Courses } from '/imports/api/courses/courses';

const videos = [
  {
    videos: {
      v35: 'https://content.jwplatform.com/players/Leg4dPDD-ahYuWCf3.html',
      v2: 'https://content.jwplatform.com/players/qR4A9L0U-ahYuWCf3.html',
      v4: 'https://content.jwplatform.com/players/kzVyCP6k-ahYuWCf3.html',
      v23: 'https://content.jwplatform.com/players/aC4CMEAT-ahYuWCf3.html',
      v46: 'https://content.jwplatform.com/players/CGuATaTA-ahYuWCf3.html',
      v49: 'https://content.jwplatform.com/players/13pNHaEG-ahYuWCf3.html',
      v24: 'https://content.jwplatform.com/players/3nskh8cg-ahYuWCf3.html',
      v36: 'https://content.jwplatform.com/players/R2OJrd5w-ahYuWCf3.html',
      v40: 'https://content.jwplatform.com/players/6x25cvOI-ahYuWCf3.html',
      v42: 'https://content.jwplatform.com/players/BkWaAmSk-ahYuWCf3.html',
      v5: 'https://content.jwplatform.com/players/vjwuT6jS-ahYuWCf3.html',
      v6: 'https://content.jwplatform.com/players/AVO71KYC-ahYuWCf3.html',
      v8: 'https://content.jwplatform.com/players/rRhXYjKt-ahYuWCf3.html',
      v27: 'https://content.jwplatform.com/players/OJId6flH-ahYuWCf3.html',
      v43: 'https://content.jwplatform.com/players/qfWXv6WA-ahYuWCf3.html',
      v10: 'https://content.jwplatform.com/players/zCiSXeCW-ahYuWCf3.html',
      v18: 'https://content.jwplatform.com/players/USmsK56n-ahYuWCf3.html',
      v21: 'https://content.jwplatform.com/players/0IOorPZB-ahYuWCf3.html',
      v31: 'https://content.jwplatform.com/players/98PSXmN3-ahYuWCf3.html',
      v34: 'https://content.jwplatform.com/players/m5hviSz9-ahYuWCf3.html',
      v38: 'https://content.jwplatform.com/players/0UkiEOfJ-ahYuWCf3.html',
      v39: 'https://content.jwplatform.com/players/69thSASD-ahYuWCf3.html',
      v45: 'https://content.jwplatform.com/players/MizrEHiw-ahYuWCf3.html',
      v47: 'https://content.jwplatform.com/players/rr0Xm77P-ahYuWCf3.html',
      v3: 'https://content.jwplatform.com/players/1cmVLCYj-ahYuWCf3.html',
      v7: 'https://content.jwplatform.com/players/37M5B39g-ahYuWCf3.html',
      v11: 'https://content.jwplatform.com/players/KGoC9LMl-ahYuWCf3.html',
      v14: 'https://content.jwplatform.com/players/9g8d6cPx-ahYuWCf3.html',
      v17: 'https://content.jwplatform.com/players/MpolmGca-ahYuWCf3.html',
      v19: 'https://content.jwplatform.com/players/Z2Ija978-ahYuWCf3.html',
      v22: 'https://content.jwplatform.com/players/yFTipYRo-ahYuWCf3.html',
      v25: 'https://content.jwplatform.com/players/Cp5drfX4-ahYuWCf3.html',
      v32: 'https://content.jwplatform.com/players/GDdwqTX9-ahYuWCf3.html',
      v33: 'https://content.jwplatform.com/players/Aqt097Xa-ahYuWCf3.html',
      v9: 'https://content.jwplatform.com/players/eAm4Cpm2-ahYuWCf3.html',
      v12: 'https://content.jwplatform.com/players/Ge5M4Tsl-ahYuWCf3.html',
      v16: 'https://content.jwplatform.com/players/ckOX7Z0t-ahYuWCf3.html',
      v26: 'https://content.jwplatform.com/players/lOYn5Q8Z-ahYuWCf3.html',
      v28: 'https://content.jwplatform.com/players/7y4qQJYi-ahYuWCf3.html',
      v30: 'https://content.jwplatform.com/players/JbuY2Z2S-ahYuWCf3.html',
      v37: 'https://content.jwplatform.com/players/Ig6bpRrq-ahYuWCf3.html',
      v41: 'https://content.jwplatform.com/players/aUoYwn7U-ahYuWCf3.html',
      v44: 'https://content.jwplatform.com/players/wIby6vFT-ahYuWCf3.html',
      v1: 'https://content.jwplatform.com/players/n5B2BefX-ahYuWCf3.html',
      v13: 'https://content.jwplatform.com/players/qM0k5v7o-ahYuWCf3.html',
      v15: 'https://content.jwplatform.com/players/ZK9byzvi-ahYuWCf3.html',
      v20: 'https://content.jwplatform.com/players/Qt8xzGVq-ahYuWCf3.html',
      v29: 'https://content.jwplatform.com/players/N1j9bjYM-ahYuWCf3.html',
      v48: 'https://content.jwplatform.com/players/wkROJmeF-ahYuWCf3.html',
      v50: 'https://content.jwplatform.com/players/NzwOVcUH-ahYuWCf3.html'
    },
    video_count: 50,
    title: 'Brenda\'s Story',
    description1: 'Brenda shares her struggles. She was 315 pounds and losing hope fast. Thinking that she would forever remain at this weight, or worse, she would keep gaining more.',
    image: 'https://s3.amazonaws.com/myinslim/subfolder/4833e512-cab3-4b85-bd79-8c96d0663bbf.jpg',
    videodescription: {
      v4: 'The College Years',
      v11: 'The Start Of Lasting Weight Loss',
      v19: 'Thinking',
      v25: 'Facing Adversity',
      v26: 'Chapter 2',
      v27: 'Eating My Feelings',
      v30: 'Working Through My Feelings: Part 2',
      v45: 'They Key To Living Life: Part 5',
      v1: 'Intro',
      v3: 'Reinvention: Part 2',
      v5: 'Could I Actually Be Fat?',
      v10: 'The Shift',
      v28: 'Digesting My Feelings',
      v46: 'The Key To Living Life: Part 6',
      v16: 'Putting It All Together',
      v32: 'The Shift: Part 2',
      v35: 'Back on Track',
      v14: 'Turning Up The Heat',
      v18: 'Over Training-Quality vs Quantity',
      v22: 'Unexpected Inspiration',
      v23: 'Train Smarter Not Harder',
      v33: 'Reinvention: Part 1',
      v36: 'Feed The Machine',
      v37: 'Fat Cells',
      v38: 'Finding My Way',
      v39: 'Balancing It All Out',
      v42: 'The Key To Living Life: Part 2',
      v43: 'The Key To Living Life: Part 3',
      v44: 'The Key To Living Life: Part 4',
      v2: 'Who Am I?',
      v15: 'Putting It In Writing',
      v24: 'Indulge',
      v21: 'Sabotage',
      v31: 'The Shift: Part 1',
      v48: 'The Key To Living Life: Part 8',
      v50: 'My Final Lessons Learned',
      v6: 'The Roller Coaster',
      v7: 'Reality Bites',
      v9: 'Just The Way It Is',
      v12: 'Losing Weight Isn\'t A Straight Line',
      v13: 'Cleaning It Up',
      v40: 'Where I\'m At Now',
      v41: 'The Key To Living Life: Part 1',
      v47: 'The Key To Living Life: Part 7',
      v49: 'The Key To Living Life: Part 9',
      v8: 'What\'s Wrong With Me?',
      v17: 'Goals And Affirmations',
      v20: 'Stop Being Emotional',
      v29: 'Working Through My Feelings: Part 1'
    },
    name: 'brenda',
    subtitle: 'From 315 Pounds To An Inspiration',
    description2: 'Until the day she read some information that changed her life and helped her lose 145 pounds. An inspiration to many, Brenda shares her honest story and shows you what she learned along the way.'
  },
  {
    videos: {
      v5: 'https://content.jwplatform.com/players/Aov9unk8-ahYuWCf3.html',
      v7: 'https://content.jwplatform.com/players/oxNIJ4PS-ahYuWCf3.html',
      v20: 'https://content.jwplatform.com/players/Y0n0KnE7-ahYuWCf3.html',
      v25: 'https://content.jwplatform.com/players/ChFn12uH-ahYuWCf3.html',
      v27: 'https://content.jwplatform.com/players/w88ZWSx2-ahYuWCf3.html',
      v28: 'https://content.jwplatform.com/players/gd33k4Hp-ahYuWCf3.html',
      v39: 'https://content.jwplatform.com/players/ZIkQORRN-ahYuWCf3.html',
      v8: 'https://content.jwplatform.com/players/e3j7XKaj-ahYuWCf3.html',
      v14: 'https://content.jwplatform.com/players/k8KHYEJx-ahYuWCf3.html',
      v21: 'https://content.jwplatform.com/players/4jxXAknS-ahYuWCf3.html',
      v43: 'https://content.jwplatform.com/players/AvdsCRhE-ahYuWCf3.html',
      v48: 'https://content.jwplatform.com/players/wsQ5K5KJ-ahYuWCf3.html',
      v49: 'https://content.jwplatform.com/players/PQk22zI1-ahYuWCf3.html',
      v4: 'https://content.jwplatform.com/players/vc7Bygap-ahYuWCf3.html',
      v19: 'https://content.jwplatform.com/players/lyJCs8Pi-ahYuWCf3.html',
      v32: 'https://content.jwplatform.com/players/OhBIP3VX-ahYuWCf3.html',
      v36: 'https://content.jwplatform.com/players/pU8WvJ2i-ahYuWCf3.html',
      v37: 'https://content.jwplatform.com/players/BYfojXYm-ahYuWCf3.html',
      v46: 'https://content.jwplatform.com/players/T85Qi0Hk-ahYuWCf3.html',
      v1: 'https://content.jwplatform.com/players/TtAYrCOL-AyZqKQFa.html',
      v3: 'https://content.jwplatform.com/players/2pZBfK6w-ahYuWCf3.html',
      v22: 'https://content.jwplatform.com/players/zFvfGqQZ-ahYuWCf3.html',
      v35: 'https://content.jwplatform.com/players/OGz7bfrS-ahYuWCf3.html',
      v41: 'https://content.jwplatform.com/players/xb2bL2fu-ahYuWCf3.html',
      v47: 'https://content.jwplatform.com/players/cdYu5gXM-ahYuWCf3.html',
      v15: 'https://content.jwplatform.com/players/ii3Pg12Q-ahYuWCf3.html',
      v30: 'https://content.jwplatform.com/players/uyI3Eylq-ahYuWCf3.html',
      v31: 'https://content.jwplatform.com/players/ITznpI0B-ahYuWCf3.html',
      v34: 'https://content.jwplatform.com/players/CdFfvFvu-ahYuWCf3.html',
      v40: 'https://content.jwplatform.com/players/1nzjMTtV-ahYuWCf3.html',
      v2: 'http://content.jwplatform.com/players/SF4zqydt-L04SmsaB.html',
      v6: 'https://content.jwplatform.com/players/aBLPu1vV-ahYuWCf3.html',
      v16: 'https://content.jwplatform.com/players/Vs6cMRNz-ahYuWCf3.html',
      v17: 'https://content.jwplatform.com/players/U1ils3aq-ahYuWCf3.html',
      v23: 'https://content.jwplatform.com/players/JfctTtFY-ahYuWCf3.html',
      v26: 'https://content.jwplatform.com/players/1rr2uSZ2-ahYuWCf3.html',
      v29: 'https://content.jwplatform.com/players/IB9xKr6Y-ahYuWCf3.html',
      v38: 'https://content.jwplatform.com/players/2Bsnaif7-ahYuWCf3.html',
      v10: 'https://content.jwplatform.com/players/0Z5GRo7j-ahYuWCf3.html',
      v12: 'https://content.jwplatform.com/players/N7PUutJo-ahYuWCf3.html',
      v42: 'https://content.jwplatform.com/players/SpF9TnJ0-ahYuWCf3.html',
      v9: 'https://content.jwplatform.com/players/EDG3mYam-ahYuWCf3.html',
      v11: 'https://content.jwplatform.com/players/9mwuSlfr-ahYuWCf3.html',
      v13: 'https://content.jwplatform.com/players/voZ1mtYp-ahYuWCf3.html',
      v18: 'https://content.jwplatform.com/players/hxZcVrjy-ahYuWCf3.html',
      v24: 'https://content.jwplatform.com/players/KT0uAspT-ahYuWCf3.html',
      v33: 'https://content.jwplatform.com/players/ek4R2CN5-ahYuWCf3.html',
      v44: 'https://content.jwplatform.com/players/I8EqFozm-ahYuWCf3.html',
      v45: 'https://content.jwplatform.com/players/epVrkW6O-L04SmsaB.html',
      v50: 'https://content.jwplatform.com/players/obYgmOgZ-ahYuWCf3.html'
    },
    name: 'diane',
    title: 'Diane\'s Story',
    subtitle: 'Mother Of 7 Loses 150 Pounds.',
    description2: 'This course will show you how she finally gained control of her body and lost over 150 lbs in the course of 14 months. Highly educational and motivating.',
    image: 'https://s3.amazonaws.com/myinslim/subfolder/Diane-Carbonell.jpg',
    videodescription: {
      v3: 'History Of Weight Gain',
      v5: 'Aha  Moment',
      v19: 'What is Your Relationship With Food',
      v29: 'Fat Does Not Make You Fat',
      v31: 'Techniques For Saying Goodbye To Junk Food',
      v34: 'Vegetables/Fruits: Don\'t Be Low',
      v38: 'Grocery Shopping Tips And Tricks',
      v46: 'Plan Ahead For The Holidays',
      v10: '3 Reasons I Was Succesful',
      v11: 'How Much Weight Do You Want To Lose?',
      v16: 'Celebrate Small Successes',
      v28: 'All Carbs Are Not Evil',
      v43: 'Consistency Matters',
      v2: 'Childhood & Obesity',
      v4: 'Failed Dieting Attempts',
      v7: 'First Successes',
      v9: 'How Long Did it Take to Lose 150 lbs',
      v14: 'Positive Affirmations And How To Use Them',
      v18: 'The Importance Of Permanent Lifestyle',
      v24: 'Exercise Matters But Not Why You Think',
      v26: '10 Foods To Avoid Like The Plague',
      v35: 'Can You Have Dessert While Losing Weight?',
      v40: 'Eating Out',
      v12: 'Weight Loss Goals',
      v20: 'What Are Your Trigger Foods?',
      v32: 'What Proteins Are Good For Weight Loss',
      v41: 'Share Your Commitment To Weight Loss',
      v44: 'Negative Reactions',
      v49: 'Enjoy The Process',
      v15: 'Do Not Put Yourself Down',
      v22: 'Know Your Numbers',
      v48: 'Planned Indulgences',
      v6: 'First Steps At Weight Loss',
      v17: 'Visualize Yourself At Your Ideal Weight',
      v23: 'Keeping A Food Journal',
      v27: 'Why Sugar Is Detrimental',
      v39: 'What If You Don\'t Cook Much?',
      v50: 'Portion Control',
      v13: 'Being A Loner Is No Good',
      v25: 'Expect Setbacks',
      v36: 'Clean Out Your Refrigerator And Pantry',
      v37: 'How To Plan Your Meals',
      v45: 'Watch Out For Self-Sabotage',
      v1: 'Who Am I?',
      v8: 'Plateaus Happen',
      v21: 'How To Cultivate A Healthy Relationship',
      v30: 'Do Not Drink Your Calories',
      v33: 'Whole Grains: Watch The Label',
      v42: 'Weigh Regularly',
      v47: 'Dealing With Mistakes'
    },
    video_count: 50,
    description1: 'Diane will show you how her weight spiraled out of control. For years she would try to slim down but instead kept gaining more and more weight until she reached 305 lbs.'
  }];


Meteor.startup(() => {
  if (!Courses.find().count()) {
    videos.map((v) => {
      const data = {
        createdAt: new Date(),
        slug: v.name,
        title: v.title,
        subtitle: v.subtitle,
        description: v.description2,
        videoDescription: v.description1,
        image: v.image,
        videosCount: v.video_count,
        videos: []
      };

      const videoKeys = keys(v.videos);
      videoKeys.map((key) => {
        const id = parseInt(key.substring(1), 10) - 1;
        data.videos[id] = {
          title: v.videodescription[key],
          url: v.videos[key]
        };
      });

      Courses.insert(data);
    });
  }
});